### ISSUE TITLE
Explanation for hyper parameter

### ISSUE THREAD

**Issue by nghiabka** [dschinagl/gace#1]
Thank you for the excellent work. Can you explain the parameter in cfgs/gace_demo.yaml? Why is it set with the value 170?

  NORM_FACTORS: {
      'cx': 80.0,
      'cy': 80.0,
      'cz': 5.0,
      'dx': [21.0, 2.0, 4.0],
      'dy': [4.0, 2.0, 1.5], 
      'dz': [5.5, 2.5, 2.5],
      'dist': 85.0,
      'nr_pts': [70000.0, 6000.0, 6000.0],
  }
NORM_FACTORS_CP: { ‘dist’: 170.0, }

I would greatly appreciate a reply from you.

**Comment by dschinagl** [comment]
Thank you for your interest in our work!

These values are used to normalize the individual properties and correspond to the maximum values that can occur in the dataset.
NORM_FACTORS contains the normalization values for the instance-specific features of an object, and NORM_FACTORS_CP contains the normalization values for the contextual features. In the latter case, the distance between two objects can be larger than the distance between the ego vehicle and a single object (instance-specific distance).
